#!/usr/bin/env python3
"""
Post-process bridge_generated.rs for host-only or remote-only builds.

When building with --features host-only, certain functions in flutter_ffi.rs
are excluded via #[cfg(not(feature = "host-only"))]. However, bridge_generated.rs
(auto-generated by flutter_rust_bridge) still references them, causing link errors.

This script wraps the wire_* function bodies that call excluded functions with
cfg gates, so they compile to no-ops in host-only or remote-only mode.

Usage:
    python3 res/patch_bridge.py --host-only
    python3 res/patch_bridge.py --remote-only
"""

import re
import sys
import os

# Functions excluded in host-only mode (from flutter_ffi.rs cfg gates)
HOST_ONLY_EXCLUDED = {
    "peer_get_sessions_count",
    "session_add_existed_sync", "session_add_job", "session_add_port_forward",
    "session_add_sync", "session_alternative_codecs", "session_cancel_job",
    "session_change_prefer_codec", "session_change_resolution", "session_close",
    "session_close_terminal", "session_close_voice_call", "session_create_dir",
    "session_ctrl_alt_del", "session_elevate_direct", "session_elevate_with_logon",
    "session_enter_or_leave", "session_get_audit_guid", "session_get_audit_server_sync",
    "session_get_common", "session_get_common_sync", "session_get_conn_session_id",
    "session_get_conn_token", "session_get_custom_image_quality",
    "session_get_displays_as_individual_windows", "session_get_edge_scroll_edge_thickness",
    "session_get_enable_trusted_devices", "session_get_flutter_option",
    "session_get_image_quality", "session_get_is_recording", "session_get_keyboard_mode",
    "session_get_last_audit_note", "session_get_option", "session_get_peer_option",
    "session_get_platform", "session_get_remember", "session_get_reverse_mouse_wheel_sync",
    "session_get_rgba_size", "session_get_scroll_style", "session_get_toggle_option",
    "session_get_toggle_option_sync", "session_get_trackpad_speed",
    "session_get_use_all_my_displays_for_the_remote_session", "session_get_view_style",
    "session_handle_flutter_key_event", "session_handle_flutter_raw_key_event",
    "session_handle_screenshot", "session_input_key", "session_input_os_password",
    "session_input_string", "session_is_keyboard_mode_supported",
    "session_is_multi_ui_session", "session_load_last_transfer_jobs",
    "session_lock_screen", "session_login", "session_new_rdp",
    "session_next_rgba", "session_on_waiting_for_image_dialog_show",
    "session_open_terminal", "session_peer_option", "session_printer_response",
    "session_read_dir_to_remove_recursive", "session_read_local_dir_sync",
    "session_read_local_empty_dirs_recursive_sync", "session_read_remote_dir",
    "session_read_remote_empty_dirs_recursive_sync", "session_reconnect",
    "session_record_screen", "session_refresh", "session_register_gpu_texture",
    "session_register_pixelbuffer_texture", "session_remove_all_empty_dirs",
    "session_remove_file", "session_remove_port_forward", "session_rename_file",
    "session_request_new_display_init_msgs", "session_request_voice_call",
    "session_resize_terminal", "session_restart_remote_device", "session_resume_job",
    "session_send", "session_send_chat", "session_send_files", "session_send_mouse",
    "session_send_note", "session_send_pointer", "session_send_selected_session_id",
    "session_send_terminal_input", "session_set_audit_guid",
    "session_set_confirm_override_file", "session_set_custom_fps",
    "session_set_custom_image_quality", "session_set_displays_as_individual_windows",
    "session_set_edge_scroll_edge_thickness", "session_set_flutter_option",
    "session_set_image_quality", "session_set_keyboard_mode",
    "session_set_reverse_mouse_wheel", "session_set_scroll_style",
    "session_set_size", "session_set_trackpad_speed",
    "session_set_use_all_my_displays_for_the_remote_session",
    "session_set_view_style", "session_start", "session_start_with_displays",
    "session_switch_display", "session_switch_sides", "session_take_screenshot",
    "session_toggle_option", "session_toggle_privacy_mode",
    "session_toggle_virtual_display", "session_send2fa",
}

# Functions excluded in remote-only mode
REMOTE_ONLY_EXCLUDED = {
    # server/cm related functions - add as needed when remote-only build fails
}


def patch_bridge_generated(filepath, mode):
    """Patch bridge_generated.rs by wrapping excluded function wire_ bodies."""
    if not os.path.exists(filepath):
        print(f"Warning: {filepath} not found, skipping")
        return

    with open(filepath, 'r') as f:
        content = f.read()

    excluded = HOST_ONLY_EXCLUDED if mode == 'host-only' else REMOTE_ONLY_EXCLUDED
    feature = 'host-only' if mode == 'host-only' else 'remote-only'

    patched_count = 0
    for func_name in excluded:
        wire_name = f"wire_{func_name}"
        # Match: pub fn wire_session_xxx(... ) {
        # We need to find the function and replace its body
        pattern = rf'(pub fn {wire_name}\([^)]*\)\s*\{{)'
        matches = list(re.finditer(pattern, content))
        for match in matches:
            start = match.end()
            # Find matching closing brace
            depth = 1
            pos = start
            while pos < len(content) and depth > 0:
                if content[pos] == '{':
                    depth += 1
                elif content[pos] == '}':
                    depth -= 1
                pos += 1
            if depth == 0:
                body = content[start:pos-1]
                # Wrap original body with cfg and add empty fallback
                new_body = f"""
    #[cfg(not(feature = "{feature}"))]
    {{{body}}}
    #[cfg(feature = "{feature}")]
    {{}}"""
                content = content[:start] + new_body + content[pos-1:]
                patched_count += 1

    with open(filepath, 'w') as f:
        f.write(content)

    print(f"Patched {patched_count} wire functions in {filepath} for {mode} mode")


def patch_bridge_io(filepath, mode):
    """Patch bridge_generated.io.rs similarly."""
    if not os.path.exists(filepath):
        print(f"Warning: {filepath} not found, skipping")
        return

    with open(filepath, 'r') as f:
        content = f.read()

    excluded = HOST_ONLY_EXCLUDED if mode == 'host-only' else REMOTE_ONLY_EXCLUDED
    feature = 'host-only' if mode == 'host-only' else 'remote-only'

    patched_count = 0
    for func_name in excluded:
        wire_name = f"wire_{func_name}"
        pattern = rf'(pub fn {wire_name}\([^)]*\)\s*\{{)'
        matches = list(re.finditer(pattern, content))
        for match in matches:
            start = match.end()
            depth = 1
            pos = start
            while pos < len(content) and depth > 0:
                if content[pos] == '{':
                    depth += 1
                elif content[pos] == '}':
                    depth -= 1
                pos += 1
            if depth == 0:
                body = content[start:pos-1]
                new_body = f"""
    #[cfg(not(feature = "{feature}"))]
    {{{body}}}
    #[cfg(feature = "{feature}")]
    {{}}"""
                content = content[:start] + new_body + content[pos-1:]
                patched_count += 1

    with open(filepath, 'w') as f:
        f.write(content)

    print(f"Patched {patched_count} wire functions in {filepath} for {mode} mode")


if __name__ == '__main__':
    if len(sys.argv) < 2 or sys.argv[1] not in ('--host-only', '--remote-only'):
        print(f"Usage: {sys.argv[0]} --host-only|--remote-only")
        sys.exit(1)

    mode = sys.argv[1].lstrip('-')
    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    patch_bridge_generated(os.path.join(base, 'src', 'bridge_generated.rs'), mode)
    patch_bridge_io(os.path.join(base, 'src', 'bridge_generated.io.rs'), mode)
    print(f"Bridge patching complete for {mode} mode")
