#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/rustdesk/rustdesk /usr/bin/rustdesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/shopremote2.service ]; then
			rm /etc/systemd/system/shopremote2.service /usr/lib/systemd/system/shopremote2.service /usr/lib/systemd/user/shopremote2.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/shopremote2/files/systemd/shopremote2.service /usr/lib/systemd/system/shopremote2.service
		# try fix error in Ubuntu 18.04
		# Failed to reload shopremote2.service: Unit shopremote2.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/shopremote2.service:10: Executable path is not absolute: pkill -f "shopremote2 --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/shopremote2.service
		fi
		systemctl daemon-reload
		systemctl enable shopremote2
		systemctl start shopremote2
	fi
fi
